version: '3'

services:
  python:
    image: python:3.9-slim
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash
    depends_on:
      - postgres
      - elasticsearch

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ../postgresql:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} # from .env
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} # from .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    user: "elasticsearch"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  nifi:
    image: apache/nifi:latest
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTP_PORT=8443

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  airflow-webserver:
    image: apache/airflow:2.7.1-python3.9
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/mydatabase
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/mydatabase
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - airflow-scheduler
    volumes:
      - ../airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.1-python3.9
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/mydatabase
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/mydatabase
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ../airflow:/opt/airflow
    command: scheduler


  airflow-worker:
    image: apache/airflow:2.7.1-python3.9
    command: celery worker
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/mydatabase
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/mydatabase
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
    depends_on:
      - airflow-webserver
    volumes:
      - ../airflow:/opt/airflow

volumes:
  postgres_data:
  dags_folder:
  pgadmin_data:
