# Dockerfile.airflow-webserver
FROM apache/airflow:2.7.1-python3.9

USER root
# Copy entrypoint script
COPY ./airflow/webserver/entrypoint.sh /entrypoint.sh

# Make the script executable
RUN chmod +x /entrypoint.sh

USER airflow